"""Oque esse módulo faz

TESTE   TESTE   TESTE   TESTE   TESTE   TESTE   TESTE   TESTE   TESTE   TESTE
TESTE   TESTE   TESTE   TESTE   TESTE   TESTE   TESTE   TESTE   TESTE   TESTE
TESTE   TESTE   TESTE   TESTE   TESTE   TESTE   TESTE   TESTE   TESTE   TESTE
TESTE   TESTE   TESTE   TESTE   TESTE   TESTE   TESTE   TESTE   TESTE   TESTE
TESTE   TESTE   TESTE   TESTE   TESTE   TESTE   TESTE   TESTE   TESTE   TESTE
TESTE   TESTE   TESTE   TESTE   TESTE   TESTE   TESTE   TESTE   TESTE   TESTE
TESTE   TESTE   TESTE   TESTE   TESTE   TESTE   TESTE   TESTE   TESTE   TESTE
TESTE   TESTE   TESTE   TESTE   TESTE   TESTE   TESTE   TESTE   TESTE   TESTE

"""