from pathlib import Path

ROOTR_DIR = Path(__file__).parent
FILES_DIR = ROOTR_DIR / 'files'
WINDOW_ICON_PATH = FILES_DIR / 'icon.png'


#colors
PRIMARY_COLOR = '#1e81b0'
DARKER_PRIMARY_COLOR = '#16658a'
DARKEST_PRIMARY_COLOR = '#115270'

#Sizing
BIG_FONT_SIZE = 40
MEDIUM_FONT_SIZE = 24
SMALL_FONT_SIZE = 18
TEXT_MAGIN = 15
MINIMUN_WIDTH = 500